"""Schema hints for Shopify DLT pipeline."""

from .schemas import (
    ORDER_COLUMNS,
    LINE_ITEM_COLUMNS,
    REFUND_COLUMNS,
    REFUND_LINE_ITEM_COLUMNS,
    ORDER_ADJUSTMENT_COLUMNS,
    DISCOUNT_APPLICATION_COLUMNS,
    TAX_LINE_COLUMNS,
    SHIPPING_LINE_COLUMNS,
    DISCOUNT_ALLOCATION_COLUMNS,
    ORDER_HINTS,
    CUSTOMER_COLUMNS,
    CUSTOMER_HINTS,
    SHOP_COLUMNS,
)

__all__ = [
    "ORDER_COLUMNS",
    "LINE_ITEM_COLUMNS",
    "REFUND_COLUMNS",
    "REFUND_LINE_ITEM_COLUMNS",
    "ORDER_ADJUSTMENT_COLUMNS",
    "DISCOUNT_APPLICATION_COLUMNS",
    "TAX_LINE_COLUMNS",
    "SHIPPING_LINE_COLUMNS",
    "DISCOUNT_ALLOCATION_COLUMNS",
    "ORDER_HINTS",
    "CUSTOMER_COLUMNS",
    "CUSTOMER_HINTS",
    "SHOP_COLUMNS",
]
