"""Configuration module for Shopify DLT pipeline."""

from .settings import (
# API Configuration
SHOPIFY_API_VERSION,
MAX_RETRIES,
REQUEST_TIMEOUT,

# PII Hashing
PII_HASH_SECRET,

# Incremental Loading
FETCH_LAST_DAYS,
INCREMENTAL_LOOKBACK_DAYS,

# Backfill Configuration
DEFAULT_BACKFILL_DAYS,
MAX_BACKFILL_DAYS,
BACKFILL_BATCH_DAYS,

# Chunk & Page Configuration
DEFAULT_CHUNK_DAYS,
PAGE_SIZE,
SHOPIFY_ORDERS_SNAPSHOT_LOOKBACK_DAYS,
SHOPIFY_ORDERS_HYDRATE_BATCH_SIZE,
SHOPIFY_BULK_POLL_INTERVAL_SECONDS,
SHOPIFY_ORDERS_BULK_ID_SNAPSHOT_ENABLED,

# Destination
DESTINATION,

# Database Paths
DUCKDB_PATH,

# Snowflake
SNOWFLAKE_ACCOUNT,
SNOWFLAKE_USER,
SNOWFLAKE_PASSWORD,
SNOWFLAKE_DATABASE,
SNOWFLAKE_WAREHOUSE,
SNOWFLAKE_ROLE,

# Shop Credentials
SHOPIFY_SHOP_URL,
SHOPIFY_ACCESS_TOKEN,

# Pipeline Settings
PIPELINE_NAME,
DATASET_NAME,
LOG_LEVEL,
)

__all__ = [
# API
"SHOPIFY_API_VERSION",
"MAX_RETRIES",
"REQUEST_TIMEOUT",

# PII
"PII_HASH_SECRET",

# Incremental
"FETCH_LAST_DAYS",
"INCREMENTAL_LOOKBACK_DAYS",

# Backfill
"DEFAULT_BACKFILL_DAYS",
"MAX_BACKFILL_DAYS",
"BACKFILL_BATCH_DAYS",

# Chunk & Page
"DEFAULT_CHUNK_DAYS",
"PAGE_SIZE",
"SHOPIFY_ORDERS_SNAPSHOT_LOOKBACK_DAYS",
"SHOPIFY_ORDERS_HYDRATE_BATCH_SIZE",
"SHOPIFY_BULK_POLL_INTERVAL_SECONDS",
"SHOPIFY_ORDERS_BULK_ID_SNAPSHOT_ENABLED",

# Destination
"DESTINATION",

# Database
"DUCKDB_PATH",

# Snowflake
"SNOWFLAKE_ACCOUNT",
"SNOWFLAKE_USER",
"SNOWFLAKE_PASSWORD",
"SNOWFLAKE_DATABASE",
"SNOWFLAKE_WAREHOUSE",
"SNOWFLAKE_ROLE",

# Credentials
"SHOPIFY_SHOP_URL",
"SHOPIFY_ACCESS_TOKEN",

# Pipeline
"PIPELINE_NAME",
"DATASET_NAME",
"LOG_LEVEL",
]